### ISSUE TITLE
Raw subsriptions script broken?

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/haz-sc3-producer#3]
Hi,

please could you try out cloudformation/raw-subscriptions.sh it fails with an error for me and I'm not sure why.

Ta,
G

**Comment by quiffman** [comment]
```
$ ./cloudformation/raw-subscriptions.sh haz-esb --profile=prod
subscription arn:aws:sns:ap-southeast-2:862640294325:haz-esb-haz-Y9BU65N6324:26bcde26-a5d1-4652-bc13-d395573b9ccf RawMessageDelivery = true
```

Done...?

**Comment by gclitheroe** [comment]
Ah - I did it manually on that stack.  But the fact you even get that far implies there is something about my shell env making it not work.  I'll get you to have a look with me when we're in the same building...
